export const STATUS_REASON_CODES = {
  TRIP_CREATED: 'TRIP_CREATED',
  DISPATCHER_ASSIGNED: 'DISPATCHER_ASSIGNED',
  IMMEDIATE_DISPATCH: 'IMMEDIATE_DISPATCH',
  TRIP_STARTED: 'TRIP_STARTED',
  TRIP_COMPLETED: 'TRIP_COMPLETED',
  DISPATCHER_CANCELLED: 'DISPATCHER_CANCELLED',
  CLIENT_CANCELLED: 'CLIENT_CANCELLED',
  VEHICLE_UNAVAILABLE: 'VEHICLE_UNAVAILABLE',
  DRIVER_UNAVAILABLE: 'DRIVER_UNAVAILABLE',
  WEATHER_CANCELLED: 'WEATHER_CANCELLED',
  STATUS_EDIT: 'STATUS_EDIT',
} as const;
