var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0iwn0zc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0zsfk0h.js")
R.c("server/chunks/ssr/_0hs2llg._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0b-o2f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ybk2gh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0diwgm-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/frontend_src_app_(auth)_layout_tsx_070_2w.._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_(auth)_login_page_actions_09n6yyl.js")
R.m(6338)
module.exports=R.m(6338).exports
