export enum VehicleAuditAction {
  CREATE = 'VEHICLE_CREATE',
  UPDATE = 'VEHICLE_UPDATE',
  STATUS_CHANGE = 'VEHICLE_STATUS_CHANGE',
  DELETE = 'VEHICLE_DELETE',
}

import { ENTITY_TYPES } from '@tms/shared';

export const VEHICLE_ENTITY_TYPE = ENTITY_TYPES.VEHICLE;
