/**
 * Permission keys — align with backend RBAC (see ai-docs/database-schema.md).
 * Used for UI gating once auth is implemented.
 */
/** Align with backend `prisma/seed-data.ts` permission keys. */
export const PERMISSIONS = {
  // Auth & admin
  VIEW_USERS: 'VIEW_USERS',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
  VIEW_ROLES: 'VIEW_ROLES',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_PERMISSIONS: 'VIEW_PERMISSIONS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',
  // Domain (reserved for upcoming modules)
  VIEW_TRIPS: 'VIEW_TRIPS',
  CREATE_TRIP: 'CREATE_TRIP',
  UPDATE_TRIP: 'UPDATE_TRIP',
  DELETE_TRIP: 'DELETE_TRIP',
  VIEW_VEHICLES: 'VIEW_VEHICLES',
  CREATE_VEHICLE: 'CREATE_VEHICLE',
  UPDATE_VEHICLE: 'UPDATE_VEHICLE',
  DELETE_VEHICLE: 'DELETE_VEHICLE',
  CHANGE_VEHICLE_STATUS: 'CHANGE_VEHICLE_STATUS',
  VIEW_DRIVERS: 'VIEW_DRIVERS',
  CREATE_DRIVER: 'CREATE_DRIVER',
  UPDATE_DRIVER: 'UPDATE_DRIVER',
  DELETE_DRIVER: 'DELETE_DRIVER',
  CHANGE_DRIVER_STATUS: 'CHANGE_DRIVER_STATUS',
  VIEW_CLIENTS: 'VIEW_CLIENTS',
  CREATE_CLIENT: 'CREATE_CLIENT',
  UPDATE_CLIENT: 'UPDATE_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',
  VIEW_CONTRACTS: 'VIEW_CONTRACTS',
  CREATE_CONTRACT: 'CREATE_CONTRACT',
  UPDATE_CONTRACT: 'UPDATE_CONTRACT',
  DELETE_CONTRACT: 'DELETE_CONTRACT',
  VIEW_REPORTS: 'VIEW_REPORTS',
  VIEW_DISPATCH_BOARD: 'VIEW_DISPATCH_BOARD',
  DISPATCH_ASSIGN: 'DISPATCH_ASSIGN',
  DISPATCH_TRANSITION: 'DISPATCH_TRANSITION',
  DISPATCH_MANAGE: 'DISPATCH_MANAGE',
  CONFIRM_DRIVER_ON_BEHALF: 'CONFIRM_DRIVER_ON_BEHALF',
  // Sector management
  VIEW_SECTORS: 'VIEW_SECTORS',
  CREATE_SECTOR: 'CREATE_SECTOR',
  UPDATE_SECTOR: 'UPDATE_SECTOR',
  DELETE_SECTOR: 'DELETE_SECTOR',
  CHANGE_SECTOR_STATUS: 'CHANGE_SECTOR_STATUS',
  MANAGE_SUB_SECTORS: 'MANAGE_SUB_SECTORS',
  VIEW_VEHICLE_ASSIGNMENTS: 'VIEW_VEHICLE_ASSIGNMENTS',
  ASSIGN_VEHICLE: 'ASSIGN_VEHICLE',
  TRANSFER_VEHICLE: 'TRANSFER_VEHICLE',
  UNASSIGN_VEHICLE: 'UNASSIGN_VEHICLE',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
