export const ROUTES = {
  home: '/',
  dashboard: '/dashboard',
  trips: '/trips',
  tripsNew: '/trips/new',
  tripsDetail: (id: string) => `/trips/${id}`,
  tripsEdit: (id: string) => `/trips/${id}/edit`,
  vehicles: '/vehicles',
  vehiclesNew: '/vehicles/new',
  vehiclesDetail: (id: string) => `/vehicles/${id}`,
  vehiclesEdit: (id: string) => `/vehicles/${id}/edit`,
  drivers: '/drivers',
  driversNew: '/drivers/new',
  driversDetail: (id: string) => `/drivers/${id}`,
  driversEdit: (id: string) => `/drivers/${id}/edit`,
  clients: '/clients',
  clientsNew: '/clients/new',
  clientsDetail: (id: string) => `/clients/${id}`,
  clientsEdit: (id: string) => `/clients/${id}/edit`,
  contracts: '/contracts',
  contractsNew: '/contracts/new',
  contractsDetail: (id: string) => `/contracts/${id}`,
  contractsEdit: (id: string) => `/contracts/${id}/edit`,
  sectors: '/sectors',
  sectorsNew: '/sectors/new',
  sectorsDetail: (id: string) => `/sectors/${id}`,
  sectorsEdit: (id: string) => `/sectors/${id}/edit`,
  reports: '/reports',
  dispatchBoard: '/dispatch-board',
  auditLogs: '/audit-logs',
  users: '/users',
  settings: '/settings',
  login: '/login',
  verifyOtp: '/verify-otp',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
} as const;

export const AUTH_ROUTES = [
  ROUTES.login,
  ROUTES.verifyOtp,
  ROUTES.forgotPassword,
  ROUTES.resetPassword,
] as const;
