import { ENTITY_TYPES } from '@tms/shared';

export const CONTRACT_ENTITY_TYPE = ENTITY_TYPES.CONTRACT;

export enum ContractAuditAction {
  CREATE = 'CONTRACT.CREATE',
  UPDATE = 'CONTRACT.UPDATE',
  DELETE = 'CONTRACT.DELETE',
  STATUS_CHANGE = 'CONTRACT.STATUS_CHANGE',
}
