export const SECTOR_PERMISSIONS = {
  VIEW_SECTORS: 'VIEW_SECTORS',
  CREATE_SECTOR: 'CREATE_SECTOR',
  UPDATE_SECTOR: 'UPDATE_SECTOR',
  DELETE_SECTOR: 'DELETE_SECTOR',
  MANAGE_SUB_SECTORS: 'MANAGE_SUB_SECTORS',
  VIEW_VEHICLE_ASSIGNMENTS: 'VIEW_VEHICLE_ASSIGNMENTS',
  ASSIGN_VEHICLE: 'ASSIGN_VEHICLE',
  TRANSFER_VEHICLE: 'TRANSFER_VEHICLE',
  UNASSIGN_VEHICLE: 'UNASSIGN_VEHICLE',
} as const;
