import { ENTITY_TYPES } from '@tms/shared';

export const USER_ENTITY_TYPE = ENTITY_TYPES.USER;

export enum UsersAuditAction {
  CREATE = 'USER.CREATE',
  UPDATE = 'USER.UPDATE',
  DEACTIVATE = 'USER.DEACTIVATE',
  REACTIVATE = 'USER.REACTIVATE',
  RESET_PASSWORD = 'USER.RESET_PASSWORD',
  FORCE_LOGOUT = 'USER.FORCE_LOGOUT',
}
