import { ENTITY_TYPES } from '@tms/shared';

export const DRIVER_ENTITY_TYPE = ENTITY_TYPES.DRIVER;

export enum DriverAuditAction {
  CREATE = 'DRIVER.CREATE',
  UPDATE = 'DRIVER.UPDATE',
  STATUS_CHANGE = 'DRIVER.STATUS_CHANGE',
  DELETE = 'DRIVER.DELETE',
}
