import { ENTITY_TYPES } from '@tms/shared';

export const CLIENT_ENTITY_TYPE = ENTITY_TYPES.CLIENT;

export enum ClientAuditAction {
  CREATE = 'CLIENT.CREATE',
  UPDATE = 'CLIENT.UPDATE',
  DELETE = 'CLIENT.DELETE',
  STATUS_CHANGE = 'CLIENT.STATUS_CHANGE',
}
