export enum AuthAuditAction {
  LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  LOGIN_OTP_SENT = 'AUTH_LOGIN_OTP_SENT',
  LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  OTP_VERIFY_FAILED = 'AUTH_OTP_VERIFY_FAILED',
  LOGOUT = 'AUTH_LOGOUT',
  LOGOUT_ALL = 'AUTH_LOGOUT_ALL',
  TOKEN_REFRESH = 'AUTH_TOKEN_REFRESH',
  TOKEN_REFRESH_FAILED = 'AUTH_TOKEN_REFRESH_FAILED',
  TOKEN_REUSE_DETECTED = 'AUTH_TOKEN_REUSE_DETECTED',
}

export const AUTH_ENTITY_TYPE = 'auth';
