var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/reports/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0gz.25w._.js")
R.c("server/chunks/ssr/node_modules_08h8cko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_13ne49x.js")
R.c("server/chunks/ssr/[root-of-the-server]__0b-o2f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ybk2gh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0diwgm-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/frontend_src_054t7v5._.js")
R.c("server/chunks/ssr/frontend__next-internal_server_app_(dashboard)_reports_page_actions_11roqgh.js")
R.m(16423)
module.exports=R.m(16423).exports
